icecast:
  container_name: icecast
  hostname: icecast
  build: icecast/.
  ports:
   - 8000:8000
  volumes:
   - ../../conf/icecast2:/etc/icecast2
   - ../../logs:/var/log
liquidsoap:
  container_name: liquidsoap
  hostname: liquidsoap
  build: liquidsoap/.
  volumes:
   - ../../conf/liquidsoap:/etc/liquidsoap
   - ../../logs:/var/log
  links:
   - icecast
